# Generated by Django 3.2.2 on 2023-12-19 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='creado',
            field=models.DateTimeField(auto_now=True, verbose_name='creado'),
        ),
    ]
